[default]
extend-ignore-identifiers-re = [
    "ue", "nd", "lok", "Thm",
    "sur", "leasure", "asure", "nulll", "finf",
    "iy", "ERROR_FILENAME_EXCED_RANGE", "FLE",
    "nam", "ND", "eisDST", "inh", "Vai", "VAI",
    "fo", "hel", "IST", "Commun", "constrait",
    "cutted"
]
