name: Std Tests [GCC] - Ubuntu
on: [push, pull_request]

jobs:
  build-and-exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julelang/ci@main

      - name: Test - std::internal::conv
        run: |
          julec test --compiler gcc -o test std/internal/conv
          ./test

      - name: Test - std::internal::fastbytes
        run: |
          julec test --compiler gcc -o test std/internal/fastbytes
          ./test

      - name: Test - std::encoding::ascii85
        run: |
          julec test --compiler gcc -o test std/encoding/ascii85
          ./test

      - name: Test - std::encoding::base32
        run: |
          julec test --compiler gcc -o test std/encoding/base32
          ./test

      - name: Test - std::hash::adler32
        run: |
          julec test --compiler gcc -o test std/hash/adler32
          ./test

      - name: Test - std::hash::fnv
        run: |
          julec test --compiler gcc -o test std/hash/fnv
          ./test

      - name: Test - std::maps
        run: |
          julec test --compiler gcc -o test std/maps
          ./test

      - name: Test - std::math::big
        run: |
          julec test --compiler gcc -o test std/math/big
          ./test

      - name: Test - std::net
        run: |
          julec test --compiler gcc -o test std/net
          ./test

      - name: Test - std::slices
        run: |
          julec test --compiler gcc -o test std/slices
          ./test
