name: Std Tests [Clang] - Ubuntu
on: [push, pull_request]

jobs:
  build-and-exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Panquesito7/setup-jule@v1.1.3
        with:
          version: dev
          directory: .
          add-to-path: true

      - name: Test - std::math::big
        run: |
          julec test --compiler gcc -o test std/math/big
          ./test
