name: Tests [Clang] - Windows
on: [push, pull_request]

jobs:
  build-and-exec:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julelang/ci@main

      - name: Test - Standard Library
        run: |
          .\bin\julec --compiler clang -o test tests/std
          ./test

      - name: Test - Arrays
        run: |
          .\bin\julec --compiler clang -o test tests/arrays
          ./test

      - name: Test - Basic Calculator
        run: |
          .\bin\julec --compiler clang -o test tests/basic_calculator

      - name: Test - Comptime
        run: |
          .\bin\julec --compiler clang -o test tests/comptime
          ./test

      - name: Test - Concurrency
        run: |
          .\bin\julec --compiler clang -o test tests/concurrency
          ./test

      - name: Test - Exceptionals
        run: |
          .\bin\julec --compiler clang -o test tests/exceptionals
          ./test

      - name: Test - Generics
        run: |
          .\bin\julec --compiler clang -o test tests/generics
          ./test

      - name: Test - Levenshtein Distance
        run: |
          .\bin\julec --compiler clang -o test tests/levenshtein_distance
          ./test

      - name: Test - Maps
        run: |
          .\bin\julec --compiler clang -o test tests/maps
          ./test

      - name: Test - Operator Overloading
        run: |
          .\bin\julec --compiler clang -o test tests/operator_overloading
          ./test

      - name: Test - QuickSort
        run: |
          .\bin\julec --compiler clang -o test tests/quicksort
          ./test

      - name: Test - Sleep
        run: |
          .\bin\julec --compiler clang -o test tests/sleep
          ./test

      - name: Test - Syntax
        run: |
          .\bin\julec --compiler clang -o test tests/syntax
          ./test

      - name: Test - Traits
        run: |
          .\bin\julec --compiler clang -o test tests/traits
          ./test